### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prabhleenn**
Fixed the issue of indexing 
thanks for the opportunity.

### CODE REVIEW

**Comment by prabhleenn** [comment]
Fixed the issue of indexing
thanks for the opportunity.

**Comment by aaryan2134** [comment]
Please resolve conflicts

**Review by prabhleenn — COMMENTED** [review]
please check the revised file.

**Comment by aaryan2134** [comment]
Still there are conflicts...

**Comment by aaryan2134** [comment]
Are you working on this?

**Pull request closed without merging**
