### PR TITLE
Added Object Oriented Programming Resources

### PR DESCRIPTION
**Pull request by noobtdbs**
Screenshot 2022-10-18 181951
Screenshot 2022-10-18 181919

### CODE REVIEW

**Comment by aaryan2134** [comment]
Please resolve conflicts

**Comment by aaryan2134** [comment]
Looks good otherwise
Thank you for your contribution

**Comment by aaryan2134** [comment]
Conflicts still there. Please look into it
Thank you

**Comment by noobtdbs** [comment]
sorry for the inconvenience. Please recheck it once.

**Comment by aaryan2134** [comment]
Great work!
Thank you for your contribution

**Pull request merged**
