### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NeeravParakh**
Added "Josh Starmer's Machine Learning Playlist" in Machine Learning Resources

### CODE REVIEW

**Comment by aaryan2134** [comment]
If you are contributing for hacktoberfest you need to add atleast 5 resources. Check out the contributing guidelines for more details.
If you are not doing it for hacktoberfest then let me know

**Comment by NeeravParakh** [comment]
Contributing for hacktoberfest , will add 4 more resources.

**Comment by aaryan2134** [comment]
Please resolve merging conflicts

**Comment by aaryan2134** [comment]
Are you still working on this? or should I close this?

**Pull request closed without merging**
