### PR TITLE
Added the resource  for Operating System

### PR DESCRIPTION
**Pull request by AshishSharma1203**
Added 5 resources for Operating System including playlist in both English and Hindi,sheets, notes and last-minute revision notes.

### CODE REVIEW

**Comment by aaryan2134** [comment]
Please add this section in the index as well

**Comment by AshishSharma1203** [comment]
> Please add this section in the index as well

I have made the required changes please approve it and merge this PR . And please add a hacktoberfest label to it .

**Comment by aaryan2134** [comment]
Great work!
Please resolve conflicts so that merging can be done

**Comment by AshishSharma1203** [comment]
> Great work! Please resolve conflicts so that merging can be done

Please check whether it's okay or now. I have removed the conflicts.

**Comment by aaryan2134** [comment]
Looks good!
Thank you for your contribution

**Pull request merged**
