### PR TITLE
added more topics in the links to college subjects and then add it in the contents as well #129

### PR DESCRIPTION
**Pull request by AnushkaTiwari2**

### CODE REVIEW

**Comment by AnushkaTiwari2** [comment]
added more topics in the links to college subjects

**Comment by AnushkaTiwari2** [comment]
add more topics in the links to college subjects

**Comment by aaryan2134** [comment]
Please resolve conflicts
And you need to add minimum 5 resources if you are contributing for hacktoberfest

**Comment by AnushkaTiwari2** [comment]
ok , I am sending a new PR . with no conflicts 
and with more resources.

**Pull request closed without merging**
