### PR TITLE
Added Love Babbar DSA Sheet

### PR DESCRIPTION
**Pull request by killerraj369**
Hey,
Love Babbar DSA sheet is a must for students preparing for placement in college.
Kindly Merge the PR

### CODE REVIEW

**Comment by aaryan2134** [comment]
Please add it to the readme as well.

**Comment by killerraj369** [comment]
@aaryan2134 Done. I have updated Readme too.

**Comment by aaryan2134** [comment]
The index link is not pointing to the section.
Also, as you have added a google drive link there is no need to create a directory for the sheets

**Comment by killerraj369** [comment]
Ok, I am updating in CS Resources Directory

**Comment by killerraj369** [comment]
I have updated Readme. You can view and merge the PR
Screenshot_1

**Comment by aaryan2134** [comment]
If you are contributing for hacktoberfest you need to add atleast 5 resources. Check out the contributing guidelines for more details.
If you are not doing it for hacktoberfest then let me know

**Comment by aaryan2134** [comment]
Are you still working on this?

**Pull request closed without merging**
