### PR TITLE
created readme once again plz check

### PR DESCRIPTION
**Pull request by Swastik200**
plz check and confirm

### CODE REVIEW

**Comment by aaryan2134** [comment]
The formatting is not as per the guidelines. Please look into it
image

**Comment by aaryan2134** [comment]
Also remove the roadmap directory and files

**Comment by aaryan2134** [comment]
image
Please look into the formatting and follow the other already added resources

**Comment by aaryan2134** [comment]
Also you need to add some explanation about how this roadmap is supposed to be followed. Currently this is a combination of multiples category of resources added together

**Comment by Swastik200** [comment]
Ok, will do that.

**Comment by aaryan2134** [comment]
image
Please correct the formatting
Also please resolve conflicts before your request can be merged

**Comment by Swastik200** [comment]
Sure, will do that. But which formatting bit confused now

**Comment by aaryan2134** [comment]
https://github.com/Swastik200/Engineering-Resources
You can see your fork here
Your roadmap section is not formatted same way as the rest of the sections

**Comment by Swastik200** [comment]
plz make me understand...not getting the reason why its not coming

**Comment by aaryan2134** [comment]
You can add it by copying another section and editing the text inside those

**Comment by Swastik200** [comment]
Ok, will do that.

**Comment by aaryan2134** [comment]
Are you still working on this? or should I close this?

**Comment by Swastik200** [comment]
Honestly not getting the clue ...

**Comment by aaryan2134** [comment]
Okay no issues. 
You can brush up your markdown from [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 
I will be closing this for now then

**Pull request closed without merging**
