### PR TITLE
Fix #109 > MUI resources added !

### LINKED ISSUE #109: Add Material UI Resources !
I want to add Material UI resources under web development section as it is one of the most popular React component library. If it's relevant to the project, assign it to me, I'll have a check !

### PR DESCRIPTION
**Pull request by rohitroy-github**
I added the MUI resources to the README file/ list of resources ! 
Please have a check and merge. This is a hacktoberfest addition as well. 

#109 > done 

image

### CODE REVIEW

**Comment by aaryan2134** [comment]
Please add this section in the index as well. Looks good otherwise

**Comment by rohitroy-github** [comment]
@aaryan2134, alright.

**Comment by rohitroy-github** [comment]
I made the changes. Please have a check and merge my PR asap along with the required labels for hacktoberfest.

**Comment by aaryan2134** [comment]
Link in the index is not pointing to the section. Please look into it

**Comment by rohitroy-github** [comment]
@aaryan2134, have a check now ?

**Comment by aaryan2134** [comment]
Awesome!
Thank you

**Comment by rohitroy-github** [comment]
Is it working now ?

**Comment by rohitroy-github** [comment]
Cool

**Pull request merged**
