### PR TITLE
added more topics in the links to college subjects and then add it in the contents as well #129 

### PR DESCRIPTION
**Pull request by AnushkaTiwari2**
Added more than 5 resources

### CODE REVIEW

**Comment by aaryan2134** [comment]
image
Please correct the formatting

**Comment by aaryan2134** [comment]
Also please add this section to the index as well.

**Comment by AnushkaTiwari2** [comment]
But I have added each and every thing in a proper way. but not able to undersatnd that why its coming like this in yours. 

So, can you see this and suggest me what's the issue .
Screenshot (704)

**Comment by aaryan2134** [comment]
Looks good.
Could you please add this section to the index as well?

**Pull request merged**
