### PR TITLE
removed unnecessary anchor tags

### PR DESCRIPTION
**Pull request by slashgk**
Issue: https://github.com/aaryan2134/Engineering-Resources/issues/54

### CODE REVIEW

**Comment by aaryan2134** [comment]
None of the links are working. Please rectify the issue

**Comment by slashgk** [comment]
> None of the links are working. Please rectify the issue

@aaryan2134 Fixed.

**Comment by aaryan2134** [comment]
Please resolve conflicts

**Comment by slashgk** [comment]
> Please resolve conflicts

Done.

**Comment by aaryan2134** [comment]
Looks good
Thank you for your contribution

**Pull request merged**
