### PR TITLE
Typing speed

### PR DESCRIPTION
**Pull request by shwetmala55**

### CODE REVIEW

**Comment by aaryan2134** [comment]
https://github.com/aaryan2134/Engineering-Resources/blob/main/Projects/PROJECTS.md
Please refer the guidelines
This project does not relate to or explain anything related to the curriculum

**Comment by aaryan2134** [comment]
https://github.com/aaryan2134/Engineering-Resources/pull/12
You can read this for more details

**Comment by shwetmala55** [comment]
So i just need to update the readme file and add few links to python documentations? if so.. plz give me a day

**Comment by aaryan2134** [comment]
Yes. You need to basically explain the various subject you learnt from the project
Like basics of programming, OOPS, DBMS, etc and how they have been used in your project

**Comment by aaryan2134** [comment]
Sure. You can take your time

**Comment by shwetmala55** [comment]
plz review

**Comment by aaryan2134** [comment]
Looks good. Please add it in the Projects.md file as well

**Comment by shwetmala55** [comment]
@aaryan2134 done.

**Comment by aaryan2134** [comment]
Thank you for your contribution!

**Pull request merged**
