### PR TITLE
Added CS Resources

### PR DESCRIPTION
**Pull request by Mahich123**
Computer Science Resources has been updated now . Kindly Check the changes .

### CODE REVIEW

**Comment by aaryan2134** [comment]
Thank you for your contribution!

**Comment by aaryan2134** [comment]
If you are contributing for hacktoberfest you need to add atleast 5 resources. Check out the contributing guidelines for more details.
If you are not doing it for hacktoberfest then let me know

**Comment by Mahich123** [comment]
@aaryan2134  Done with the changes you can check it now.

**Comment by aaryan2134** [comment]
Great work!
Thank you for your contribution

**Pull request merged**
