### PR TITLE
Added TODO List project

### PR DESCRIPTION
**Pull request by kritsss**
I have added the TODO List project , kindly review the issue #35 and merge this PR. Thank you

### CODE REVIEW

**Comment by aaryan2134** [comment]
https://github.com/aaryan2134/Engineering-Resources/pull/12
You can refer this or read the contributing guidelines
Currently, this is not as per the guidelines

**Comment by aaryan2134** [comment]
Let me know if you would be working on this

**Comment by kritsss** [comment]
Yes, I will work on this

**Comment by kritsss** [comment]
Hey @aaryan2134 I have made the changes according to guidelines, please review them.

**Comment by aaryan2134** [comment]
Please correct the link. It is not working currently
Please make it point to your project's directory

**Comment by kritsss** [comment]
Hi, I've done it. Please check if it's working now.

**Pull request merged**
