### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Ritu-2001**
Make all the changes and upload it ,Please check it

### CODE REVIEW

**Comment by Ritu-2001** [comment]
Actually this is  first  time i am taking part in an open source contribution program, I am not that much familiar with Git , I think for that i am doing mistakes again and again to edit README properly and also other mistakes,,,,,, this time I am trying to make it perfect and make all the changes as you mention ,please check it and merge it.

**Comment by aaryan2134** [comment]
No issues
Feel free to ask any doubts

**Comment by aaryan2134** [comment]
Looks good now
Please add the project directory in the projects readme as well
https://github.com/aaryan2134/Engineering-Resources/blob/main/Projects/PROJECTS.md

**Comment by Ritu-2001** [comment]
add README in project directory .

**Comment by aaryan2134** [comment]
Great work!
Thank you for your contribution!
All the best for your open source journey

You can continue contributing [here](https://github.com/aaryan2134/JPMC-Quant-Challenge-2022) or to this project itself

**Comment by Ritu-2001** [comment]
Thank you so much.

**Pull request merged**
